name: NautilusManager
version: '${project.version}'
main: org.nautilusmc.nautilusmanager.NautilusManager
api-version: 1.19
authors: [MaliciousFiles, longbread, Pants]
description: Runs the Nautilus Minecraft server.
commands:
  cosmetics:
    description: Base command for cosmetics.
    usage: /cosmetics <subcommand> [args]
  nickname:
    description: Gets a player's nickname. Only available to staff.
    usage: /nickname <list|original|nickname> [page|name]
  formatting:
    description: Help command for sponsor chat formatting.
    usage: /formatting [code|name] [page]
  chat:
    description: Toggles between individual chats and global chat.
    usage: /chat [name]
  reply:
    description: Replies to last msg
    usage: /reply
    aliases: r
  msg:
    description: Sends a private message
    usage: /msg <player> <message>
    aliases:
      - tell
      - w
  afk:
    description: Toggle AFK status
    usage: /afk [player]
#  home:
#    description: Manage homes
#    usage: /home <del|set|tp> <name>
  buyhome:
    description: Trades diamond blocks for another home (max 15)
    usage: /buyhome