name: NautilusManager
version: '${project.version}'
main: org.nautilusmc.nautilusmanager.NautilusManager
api-version: 1.19
authors: [MaliciousFiles, longbread, Pants]
description: Runs the Nautilus Minecraft server.
depend:
  - PluginManager
commands:
  cosmetics:
    description: Base command for cosmetics.
    usage: /cosmetics <subcommand> [args]
  nickname:
    description: Gets a player's nickname. Only available to staff.
    usage: /nickname <list|original|nickname|set> [page|name]
  formatting:
    description: Help command for sponsor chat formatting.
    usage: /formatting [code|name] [page]
  chat:
    description: Toggles between individual chats and global chat.
    usage: /chat [name]
  reply:
    description: Replies to last msg
    usage: /reply
    aliases: r
  msg:
    description: Sends a private message
    usage: /msg <player> <message>
    aliases:
      - tell
      - w
  chatmsg:
    description: Sends a message to a specific chat
    usage: /chatmsg <chat> <message>
    aliases:
      - cm
  afk:
    description: Toggle AFK status
    usage: /afk [player]
  home:
    description: Teleport to a set home
    usage: /home <name>
  sethome:
    description: Create a new home
    usage: /sethome <name>
  delhome:
    description: Delete an existing home
    usage: /delhome <name>
  homes:
    description: List all homes
    usage: /homes
  spawn:
    description: Teleport to spawn
    usage: /spawn
  back:
    description: Teleport to the location you last teleported from
    usage: /back
  buyhome:
    description: Trades diamond blocks for another home (max 15)
    usage: /buyhome
  reloadnautilus:
    description: Reloads the plugin. Devs only.
    usage: /reloadnautilus
  tpa:
    description: Requests to teleport to a player
    usage: /tpa <player>
  tpahere:
    description: Requests a player to teleport to you
    usage: /tpahere <player>
  tpaccept:
    description: Accepts a teleport request
    usage: /tpaccept <player>
    aliases:
      - tpyes
  tpdeny:
    description: Denies a teleport request
    usage: /tpdeny <player>
    aliases:
      - tpno
  tpcancel:
    description: Cancels a teleport request
    usage: /tpcancel
  warp:
    description: Warp to a publicly available warp
    usage: /warp <name>
  createwarp:
    description: Admin command to create public warps.
    usage: /createwarp <name>
  delwarp:
    description: Admin command to remove public warps.
    usage: /delwarp <name>
  vanish:
    description: Admin command to vanish to other players.
    usage: /vanish
  suicide:
    description: Kill yourself.
    usage: /suicide
  sponsor:
    description: Get the link to become a sponsor.
    usage: /sponsor
  itemname:
    description: Set the
  #crews:
    #description: Lists all crews
    #usage: /crews
  #crew:
    #description: Base crew command
    #usage: /crew [args]
