name: NautilusManager
version: '${project.version}'
main: org.nautilusmc.nautilusmanager.NautilusManager
api-version: 1.19
authors: [MaliciousFiles, longbread, Pants, xarkenz]
description: Runs the Nautilus Minecraft server.
depend:
  - PluginManager
  - LuckPerms
commands:
  cosmetics:
    description: Edit player cosmetics.
    usage: /cosmetics <subcommand> [args...]
  nickname:
    description: Get a player's nickname. (Staff only)
    usage: /nickname <list|original|nickname|set> [page|name]
  formatting:
    description: See information about chat formatting. (Sponsor only)
    usage: /formatting [code|name] [page]
  emoji:
    description: See information about emoji shortcuts.
    usage: /emoji <list|search> [page|query]
  chat:
    description: Toggle between individual chats and global chat.
    usage: /chat <all|player> [name]
  reply:
    description: Reply to the last message.
    usage: /reply <message>
    aliases: r
  msg:
    description: Send a private message.
    usage: /msg <player> <message>
    aliases:
      - tell
      - w
  chatmsg:
    description: Send a message to a specific chat.
    usage: /chatmsg <chat> <message>
    aliases:
      - cm
  afk:
    description: Toggle AFK status.
    usage: /afk [player]
  home:
    description: Teleport to a set home.
    usage: /home <name>
  homes:
    description: List all set homes.
    usage: /homes
  sethome:
    description: Set a new home at the current location.
    usage: /sethome <name>
  delhome:
    description: Delete an existing home.
    usage: /delhome <name>
  buyhome:
    description: Buy the capacity to have another home using diamond blocks.
    usage: /buyhome
  spawn:
    description: Teleport to the global spawn area.
    usage: /spawn
  back:
    description: Teleport back to the location you last teleported from.
    usage: /back
  reloadnautilus:
    description: Reload the Nautilus plugins. (Staff only)
    usage: /reloadnautilus
  tpa:
    description: Request to teleport to a player.
    usage: /tpa <player>
  tpahere:
    description: Request a player to teleport to you.
    usage: /tpahere <player>
  tptrust:
    description: Trusts a player to tp to you without a request
    usage: /tptrust <player>
  tptrustlist:
    description: Lists the currently trusted players
    usage: /tptrustlist
  tpaccept:
    description: Accept an incoming teleport request.
    usage: /tpaccept [player]
    aliases:
      - tpyes
  tpdeny:
    description: Deny an incoming teleport request.
    usage: /tpdeny [player]
    aliases:
      - tpno
  tpcancel:
    description: Cancel the outgoing teleport request.
    usage: /tpcancel
  warp:
    description: Teleport to a publicly available warp.
    usage: /warp <name>
  createwarp:
    description: Create a public warp. (Staff only)
    usage: /createwarp <name>
  delwarp:
    description: Delete a public warp. (Staff only)
    usage: /delwarp <name>
  vanish:
    description: Turn invisible to other players. (Staff only)
    usage: /vanish
  suicide:
    description: Take the easy way out.
    usage: /suicide
  sponsor:
    description: See information about supporting NautilusMC.
    usage: /sponsor
    aliases:
      - support
  itemname:
    description: Set the name of the currently held item.
    usage: /itemname <name>
#  crews:
#    description: List all crews on the server.
#    usage: /crews
#  crew:
#    description: Perform actions relating to crews.
#    usage: /crew [args...]
#  confirm:
#    description: Confirm a pending confirmation message.
#    usage: /confirm
#  deny:
#    description: Deny a pending confirmation message.
#    usage: /deny
#  invite:
#    description: Accept or decline a pending crew invite.
#    usage: /invite [accept|decline]
#  war:
#    description: Accept or decline a declaration of war.
#    usage: /war [accept|decline]
  toggleinvisible:
    description: Targets an item frame or armor stand's invisibility
    usage: /toggleinvisible
  mute:
    description: Personally mutes another player
    usage: /mute <player>
  mutelist:
    description: List your currently muted players
    usage: /mutelist
  ban:
    description: Ban a player
    usage: /ban <player> <time> [reason]